FROM eclipse-temurin:17-jdk-alpine

COPY target/userprofile-0.0.1-SNAPSHOT.jar app/userprofile-0.0.1-SNAPSHOT.jar

EXPOSE 8080

ARG APPLICATION_CLIENT_ID
ARG APPLICATION_CLIENT_SECRET

ENV APPLICATION_CLIENT_ID=${APPLICATION_CLIENT_ID}
ENV APPLICATION_CLIENT_SECRET=${APPLICATION_CLIENT_SECRET}

ENTRYPOINT ["java", "-jar", "app/userprofile-0.0.1-SNAPSHOT.jar"]